default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: bainur
  password: password
  # If you using docker the host should be "db"
  host: localhost
  port: 5432

development:
  <<: *default
  database: miniflix_development

test:
  <<: *default
  database: sample_project_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>